language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36
      dist: trusty
      sudo: false
    - python: 3.6
      env: TOXENV=memorytest36
      dist: trusty
      sudo: false
    - python: 3.6
      env: TOXENV=coverage-py36
      dist: trusty
      sudo: false
    - python: "pypy3.5"
      env: TOXENV=pypy3
      dist: trusty
      sudo: false
    - python: 3.4
      env: TOXENV=py34
      dist: trusty
      sudo: false
    - python: 2.7
      env: TOXENV=py27
      dist: trusty
      sudo: false
    - python: 2.7
      env: TOXENV=doctest27
      dist: trusty
      sudo: false
    - python: 2.7
      env: TOXENV=memorytest27
      dist: trusty
      sudo: false

# PyPy 2.7 seems broken on Travis at the moment,
# see https://github.com/travis-ci/travis-ci/issues/8103#issuecomment-387327744
#    - python: "pypy2.7"
#      env: TOXENV=pypy

install:
  - pip install -r requirements.txt

script:
  - tox
